const STATE = {
  INITIAL: 'INITIAL',
  TOSS: 'TOSS',
  FIRSTINNING: 'FIRSTINNING',
  SECONDINNING: 'SECONDINNING',
  RESULT: 'RESULT'
};

//const EVENT_SEQUENCE = [STATE.INITIAL, STATE.TOSS, STATE.FIRSTINNING, STATE.SECONDINNING, STATE.RESULT];

export { STATE as MATCH_STATES };